### ISSUE TITLE
glue with realtime

### ISSUE THREAD

**Issue by titoasty** [dplusic/GameLift-Nodejs-ServerSDK#1]
Hi,

I'm trying to use your ported sdk with a realtime script so I can test in local.
I'm wondering where I can use AcceptPlayerSession? I can't find any function to listen to incoming clients.
Could you help me? You seem way more advanced than me :)

**Comment by dplusic** [comment]
@titoasty 

You need to use your own method to connect clients to server instances.
[GameLift component in AWS SDK](https://docs.aws.amazon.com/AWSJavaScriptSDK/latest/AWS/GameLift.html) is between clients and AWS GameLift.
GameLift Server SDK (like this project) connects game servers to AWS GameLift.

I used [socket.io](https://socket.io) for the purpose in [this toy project](https://github.com/dplusic/ideal-computing-breaking-machine).

[This diagram](https://docs.aws.amazon.com/gamelift/latest/developerguide/gamelift-sdk-server-api-interaction-vsd.html) would be helpful.

**Comment by titoasty** [comment]
Oh wow, this diagram is exactly what I needed!
It's crystal clear now, and actually quite easy :)
Thanks a lot for your help.

**Comment by j1mmie** [comment]
Hi @dplusic - Sorry to revive a dead thread. I'm sure a lot has changed since 2019, but I'm looking to set up a custom build in AWS GameLift using NodeJS. I don't want to use the new(ish) AWS GameLift Realtime Servers.

I've got it working with GameLiftLocal, but having some trouble in the AWS UI. What would you put for the Launch Path field?

![image](https://user-images.githubusercontent.com/4650220/179327308-afc12170-f736-4a4f-ba1d-7cea631d8402.png)

Maybe a shell script that just executes `node my-script.js`?

Any advice would be greatly appreciated. Thank you
